
# This file is part of the dinFaqPlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# dinFaqPlugin routing configuration
#
# @package     dinFaqPlugin
# @subpackage  config
# @author      Nicolay N. Zyk <relo.san@gmail.com>

din_faq_admin:
    class:                      'sfDoctrineRouteCollection'
    options:
        model:                  'DinFaq'
        module:                 'dinFaqAdmin'
        prefix_path:            '/adm/faq'
        column:                 'id'
        with_wildcard_routes:   true

din_faq_pair_admin:
    class:                      'sfDoctrineRouteCollection'
    options:
        model:                  'DinFaq'
        module:                 'dinFaqPairAdmin'
        prefix_path:            '/adm/faq/category/:category_id/pairs'
        column:                 'id'
        with_wildcard_routes:   true

din_faq_category_admin:
    class:                      'sfDoctrineRouteCollection'
    options:
        model:                  'DinFaqCategory'
        module:                 'dinFaqCategoryAdmin'
        prefix_path:            '/adm/faq/category'
        column:                 'id'
        with_wildcard_routes:   true

#EOF